### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by supercasey2000** [saiemgilani/cfbscrapR#11]
Hello, hopefully this is not a problem on my end, but when I run "devtools::install_github(repo="meysubb/cfbscrapR" (or when I use the other option, I get the following error:  Failed to install 'cfbsrapR from Github: variable names are limited to 10000 bytes'.

From what I can tell this may be an issue with the variable names in the data.  Thanks,

**Comment by saiemgilani** [comment]
Not sure if this is still an active issue. I hope not, please try re-installing from 
```devtools::install_github(repo="saiemgilani/cfbscrapR")```

If you're still having trouble, give us another shout

**Comment by supercasey2000** [comment]
Thanks for the reply, I still have this issue when I run the installation code referenced above.

**Comment by supercasey2000** [comment]
I got this to work on a different computer, haven't figured out the issue, but it is something related to my local environment.
