### ISSUE TITLE
Some column types in pbp_players_pos_2020.rds don't match earlier RDS files

### ISSUE THREAD

**Issue by titaniumtroop** [saiemgilani/cfbscrapR#17]
I cloned the cfbscrapR-data library to avoid reading the play-by-play files over the internet, which takes a bit. When trying to bind all of the play-by-play files together, I get an error that the column types don't match.

Here's the code that generates the errors (I combined several runs to show all the errors generated as I fixed them one-by-one):

```
pbp <- tibble(year = 2014:2020) %>%
+   mutate(pbp_years = map(year, ~ readRDS(paste0("/path/to/clone/cfbscrapR-data/data/rds/pbp_players_pos_", .x, ".rds")))) %>%
+   select(-c(year)) %>%
+   unnest(pbp_years) %>%
+   tibble::as.tibble()
Error: Can't combine `..1$id_play` <double> and `..7$id_play` <character>.
Error: Can't combine `..1$half` <integer> and `..7$half` <factor<dc2fe>>.
Error: Can't combine `..1$down_end` <integer> and `..7$down_end` <factor<9364a>>.
Error: Can't combine `..1$ppa` <double> and `..7$ppa` <character>.
Error: Can't combine `..1$id_drive` <double> and `..7$id_drive` <character>.
```

The 2020 dataset is the one causing the errors — all the others have the same data type.

I fixed this manually by casting the relevant column to the proper data type before unnesting. Can the 2020 column types be made consistent with the other years so they can all be combined automatically?

Thanks for the consideration. You've done great work on this package — I'm learning a lot about advanced CFB stats.

R 4.0.2, MacOS 10.15.7.

**Comment by saiemgilani** [comment]
While this is technically a data repo issue, i'll allow it. Noted, will work on it. I'll close it when I figure it out.

**Comment by saiemgilani** [comment]
I just updated the data repo with the `id_play` cast as numeric for 2020. Try it again @titaniumtroop and confirm that it is working for you now, if you don't mind. Otherwise, will close in a few days regardless.

**Comment by titaniumtroop** [comment]
Wow, that was fast. That solved it for `id_play`. There are a few other columns that generate the same error: 

- `half` (currently factor, should be integer)
- `down_end` (currently factor, should be integer)
- `ppa` (currently character, should be double)
- `id_drive` (currently character, should be double)

Thanks for looking into this!

**Comment by saiemgilani** [comment]
Aight gimme a minute, list any others (if any)

**Comment by titaniumtroop** [comment]
I fixed those 5 and it worked for me. Thanks again!

**Comment by saiemgilani** [comment]
All done, thanks for reporting it and also telling me the solution. Never mind when someone does that. Lemme know if you have any other issues and bona fortunam on your data exploration
