### ISSUE TITLE
Season Team Stats

### ISSUE THREAD

**Issue by gshelor** [saiemgilani/cfbscrapR#23]
**Describe the bug**
Using the cfb_stats_season_team() function doesn't include a "Team" column like the Season Advanced Stats function does.

**Expected behavior**
I expected there to be a Team column so that if I want to compare, say, 4th down conversion percentage between 2 teams, I know which teams I'm comparing.

**Desktop (please complete the following information):**
RStudio on a Macbook Air

**Additional context**

**Comment by saiemgilani** [comment]
Good note, I think we'll make that change. Mind giving us a code snippet of how you use the package functions for this, not for reproducibility, just curiosity

**Comment by gshelor** [comment]
I actually haven't used the package before, this was literally the first thing I did. I want to use the package to pull in data from 2019 to compare teams and get practice using the gt package to make tables, and eventually get into some deeper data analysis, but I'm still a novice so I'm just trying to get familiar with what cfbscrapR even does right now

**Comment by tyleroc5** [comment]
Kept getting this issue when trying to install it?

> ERROR: lazy loading failed for package ‘cfbscrapR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/cfbscrapR’
Error: Failed to install 'cfbscrapR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/79/0d8xdbx5281cj045lzr4fc300000gn/T//Rtmpm3C7gI/file97248bcb82f/cfbscrapR_1.0.5.tar.gz’ had non-zero exit status
