### ISSUE TITLE
CFBData API key required by April 1

### ISSUE THREAD

**Issue by tanho63** [saiemgilani/cfbscrapR#25]
**Is your feature request related to a problem? Please describe.**

As per Bill’s latest: 
https://blog.collegefootballdata.com/api-keys-available/

Some handling needs to happen here for the new API keys, on/before April 1 (ideally sooner). 

**Describe the solution you'd like**
A bit of refactoring required. I can chip in if that’s helpful.

**Comment by saiemgilani** [comment]
Thanks, Tan, you real

**Comment by saiemgilani** [comment]
https://discord.gg/xYbxD23u

**Comment by saiemgilani** [comment]
archiving repository, this suggestion was implemented in cfbfastR per suggestion.
