### ISSUE TITLE
Switch all GET requests to RETRY requests for robustness

### ISSUE THREAD

**Issue by tanho63** [saiemgilani/cfbscrapR#26]
**Is your feature request related to a problem? Please describe.**
Suggestion for best-practice - RETRY is more robust to accidental API unavailability - per https://blog.r-hub.io/2020/04/07/retry-wheel/

**Describe the solution you'd like**
Should be as simple as swapping out all instances of `httr::GET(...)` with `httr::RETRY("GET",...)` - is drop-in replacement

**Comment by saiemgilani** [comment]
archiving repository, this suggestion was implemented in cfbfastR per suggestion.
