### ISSUE TITLE
Issue with ep_after and EPA variables after failure to convert on 4th down

### ISSUE THREAD

**Issue by naterowan00** [saiemgilani/cfbscrapR#3]
Hello!

I was working with the play-by-play data, and I think I ran across an issue with how the expected points variable is reported after a failure to convert on 4th down. The EPA came back as positive for almost all failed 4th down conversions, which seemed bizarre.

I have attached a screenshot that I think shows the problem. In the 4th row, Baylor goes for it on 4th down and fails to convert, losing 5 yards. I believe that the ep_after should be -3.756, the negative value of Oklahoma's ep_before on the next play. Instead, it is reported as 1.073, which I am guessing is equivalent to the EP if Baylor had a 1st and 10 from this new location.

![cfbscrapr_problem](https://user-images.githubusercontent.com/44912190/88885709-dccb8080-d1ed-11ea-9a3b-5e14e1c5cc27.png)

I hope that made sense, let me know if it doesn't or if you need more info!

**Comment by saiemgilani** [comment]
Sounds about right. I think your interpretation is probably correct. We'll have a fix for it in the next few days. Thanks for bringing it to our attention
