### ISSUE TITLE
Function needs season_type added

### ISSUE THREAD

**Issue by rvino** [saiemgilani/cfbscrapR#8]
The `cfb_stats_game_advanced` function appears to actually only have two season type options: 'postseason' and 'both' and doesn't have a 'regular' option. 

The following
`cfb_stats_game_advanced(
  2019,
  week = 1,
  team = NULL,
  opponent = NULL,
  excl_garbage_time = FALSE,
  season_type = "regular"
)` 
produced this error
`Error: Enter valid season_type (String): regular, postseason, or both`
`Traceback:`
`1. cfb_stats_game_advanced(2019, week = 1, team = NULL, opponent = NULL, `
` .     excl_garbage_time = FALSE, season_type = "regular")`
`2. assertthat::assert_that(season_type %in% c("postseason", "both"), `
` .     msg = "Enter valid season_type (String): regular, postseason, or both")`

**Comment by saiemgilani** [comment]
Taken care of. Silly mistake, thanks for catching it. You can update

**Comment by saiemgilani** [comment]
resolved by @saiemgilani in commit [https://github.com/saiemgilani/cfbscrapR/commit/68cf659eeab96720e3583f69e9ba30747e52aa8b](url)
