### ISSUE TITLE
Error using cfb_pbp_data

### ISSUE THREAD

**Issue by michiWS1920** [saiemgilani/cfbscrapR#9]
Hey,

I tried using your package in googlecolab for the first time yesterday and could not get it to run after installing.

I tried using this code

```
pbp_2019 <- data.frame()
for(i in 1:15){
  data <- cfb_pbp_data(year = 2019, season_type = "regular", week = i, epa_wpa = TRUE) %>% mutate(week = i)
  df <- data.frame(data)
  pbp_2019 <- bind_rows(pbp_2019, df)
} 
```
To get the play by play data. Unfortunately I keep receiving the same error message.

> Warning message:
> “prediction from discrete bam models prior to 1.8-32 is deprecated, please refit”
> Error in 1:dk$nr[i]: NA/NaN argument

Im not quite sure what the error message refers to. Any help would be greatly appreciated.
Thanks alot.

**Comment by saiemgilani** [comment]
There's a commit being pushed today to fix this. We apparently were using 1.8-31 version of much to train.
